### ISSUE TITLE
jax-tqdm potential fix :)

### ISSUE THREAD

**Issue by jeremiecoullon** [mbjd/approximate_optimal_control#1]
Hello!

I was just checking out your usage of jax-tqdm and saw that it seemed to [throw an error](https://github.com/mbjd/approximate_optimal_control/blob/5927ddc8d6e41a16248570a967bbf538bc9c584f/nn_utils.py#L290).

This might be because when you call [jax.lax.scan](https://github.com/mbjd/approximate_optimal_control/blob/5927ddc8d6e41a16248570a967bbf538bc9c584f/nn_utils.py#L301) you pass in `None` into the `xs` argument and use the `length` argument instead to set the number of iterations.
It's possible that passing `jnp.arange(total_iters)` instead fixes that bug (see the usage in the [jax-tqdm readme](https://github.com/jeremiecoullon/jax-tqdm#in-jaxlaxscan)).

So [line 301](https://github.com/mbjd/approximate_optimal_control/blob/5927ddc8d6e41a16248570a967bbf538bc9c584f/nn_utils.py#L301) would become:

```python
final_carry, outputs = jax.lax.scan(f_scan, init_carry, jnp.arange(total_iters))
```

Hope this helps! and hope your project goes well :)

**Comment by mbjd** [comment]
Hey, thanks for bringing this to my attention -- very cool that you're this actively helping people properly use your library! I've stopped using that particular piece of code but will from now on be doing this for lots of slow-ish scan calls.

**Comment by jeremiecoullon** [comment]
Nice! :)
